### ISSUE TITLE
Purple blocks

### ISSUE THREAD

**Issue by DevTimur** [Laike-Endaril/Dynamic-Stealth#29] opened 2019-02-18 10:30 UTC
DynamicStealth-1.12.2.051.jar

Some models, and items now turn into purple blocks in hands.
For example, Galacticraft items.

**Comment by Laike-Endaril** [comment] 2019-02-18 23:07
Interesting...I have a vague idea of the cause, but will have to look into it further.  I'll grab Galacticraft for testing.

**Comment by Laike-Endaril** [comment] 2019-02-18 23:10
Wait...Galacticraft is a modpack, isn't it?  What is the modid on the items which are missing textures?

**Comment by Laike-Endaril** [comment] 2019-02-18 23:41
Since the related feature (fading items when entities fade) is causing multiple issues, I'll probably remove that feature for now, and possibly look for a better way of doing it later.
https://github.com/Laike-Endaril/Dynamic-Stealth/issues/31

**Comment by Syampuuh** [comment] 2019-02-19 00:11
Just to add to the affected items if it can help you find the cause, Vic's Modern Warfare's models are also affected.
https://minecraft.curseforge.com/projects/vics-modern-warfare-mod

**Comment by Laike-Endaril** [comment] 2019-02-19 00:17
Yeah, the held item fade feature had to be implemented in an extremely hacky way, so I'm not surprised it ended up causing issues.  It will be removed in the next version.

**Comment by Laike-Endaril** [comment] 2019-02-19 00:22
This should be fixed in the latest release (053).  If not, please post a new issue!

**Closed as completed by Laike-Endaril** 2019-02-19 00:22 UTC
