### ISSUE TITLE
some mobs turning the entire display a single color dependent on their agression state

### ISSUE THREAD

**Issue by supremedutchgamer** [Laike-Endaril/Dynamic-Stealth#56] opened 2019-06-22 22:30 UTC
https://docs.google.com/document/d/1X9jMO_Z14_qS5edAinMJLbmeMpxJqMypZW7b1ULZ32c/edit?usp=sharing <log because its too big for pastebin and all alternatives ive tried are non-functional at the time of writing this. i am so sorry for having to use google docs.

basically, in rare cases. looking at a mob in armor (ive had it happen with both zombies and skeletons, never with anything that doesnt show armor though) will turn the entire screen the color that the targetting reticle is supposed to be (blue for passive/idle, orange for searching and red for agressive). this makes the game unplayable until you get out of range of the mob, or you target another mob. you cant see any menu's either.

**Comment by Laike-Endaril** [comment] 2019-06-23 15:59
Interesting, I'll start looking into this

**Comment by Laike-Endaril** [comment] 2019-06-23 16:51
I've been completely unable to reproduce this so far, but I'm going to make a few changes to my rendering, and we'll have to see if it helps on your end over time I guess :/

This is *probably* a mod compat issue, but trying to figure out which mod DS is conflicting with would be very time consuming, so let's hope my changes do the job

**Comment by Laike-Endaril** [comment] 2019-06-23 17:21
Alright, I'm hoping this is fixed in the latest release (1.12.2.080), but I'm not sure since I was not able to reproduce it.

If you can test on the latest version for a while and tell me if you think it's fixed, that would be awesome.

**Comment by supremedutchgamer** [comment] 2019-06-23 22:45
just tested with everything updated. still has the exact same issue. i did manage to get a screencap of the mob in question. in the screenshot with the skeletons, its the one that isnt focussed that causes issues when focussed. https://imgur.com/a/Tp3U0jx i also have no idea what mod could cause this. as im not aware of any mods in my pack that mess with the skeleton model itsself. if i find some time ill make a clone of the pack, then add mods 1 by 1 untill it breaks.

**Comment by Laike-Endaril** [comment] 2019-06-23 22:55
Interesting...but yeah, I'm not sure what the cause is.  I'll have to look into it again.  Probably won't happen this weekend though.

Based on the screenshot, I'd think maybe the vignette is getting colorized.  If you can get the glitch to happen again, try disabling the overlay by pressing F1 and see what happens.

**Comment by Laike-Endaril** [comment] 2019-07-07 07:11
Are you still running into this issue, and if so, have you tried pressing F1 when it happens?  I've not been able to reproduce this so far.

**Comment by Laike-Endaril** [comment] 2019-07-09 08:55
This *might* be fixed in the latest release again (changed some more HUD related code).  If you get a chance, grab version 082 and see if you run into it again

**Comment by Laike-Endaril** [comment] 2019-07-16 20:55
I'm closing this one for now, due to many reasons evident in previous comments, but if it happens with the newest version, respond here and I'll re-open again :P

**Closed as completed by Laike-Endaril** 2019-07-16 20:55 UTC
