### ISSUE TITLE
Path finding crashes when spotted

### ISSUE THREAD

**Issue by Syampuuh** [Laike-Endaril/Dynamic-Stealth#11] opened 2019-01-17 00:45 UTC
Been getting pretty consistent crashes on the latest version when I'm spotted; there doesn't appear to be any particular catalysts, this could be a conflict with something else but I'm not really sure what.

https://paste.dimdev.org/cilaluzavo.mccrash
https://paste.dimdev.org/imefexemoz.mccrash

**Comment by Laike-Endaril** [comment] 2019-01-17 03:46
Yep, this one is a compatibility thing.  It's not an issue with DS, but rather some other mod which is altering the pathfinding classes and isn't handling a null right.  I haven't a clue which mod though.

I'll leave this open for now, but debugging it basically involves either you or me taking your modpack and disabling mods besides DS until it works, to figure out where the issue lies.  This could take some time, especially if the issue somehow involves a combination of more than 2 mods (rare, but it happens), so I'll be taking care of some other things before I get to filtering through those.

**Comment by Syampuuh** [comment] 2019-01-17 05:04
Gotcha. I run kind of a truckload of mods as you can see, so once I figure out what's responsible I'll let you know here.

**Comment by Laike-Endaril** [comment] 2019-01-17 06:11
Thanks, that would be helpful.  If we pinpoint a mod I can start looking into possible workarounds.

**Comment by Laike-Endaril** [comment] 2019-01-18 20:39
Hey, I started looking at this, but simply finding all your mods with the correct versions (using the crash log mod list) is difficult.  If you zip/rar/etc the modpack and make it available to me I'll go through it.

Or of course, if it's available through an online modpack via curseforge or technic, etc, I just need to know where / under what name.

**Comment by Syampuuh** [comment] 2019-01-19 21:34
Sorry, my mods are just a mish mash of stuff I've thrown together. :V 
That said, I think I've pinpointed the issue to be the flashlight/mining helmet from [Adventure Tools](https://minecraft.curseforge.com/projects/adventure-tools). Crashes are only happening when I have one of them on around mobs. From what I can tell it works by rapidly creating and removing an invisible light source block where you're looking, so maybe that block disappearing and reappearing wherever constantly is what's goofing the path finding.

**Comment by Laike-Endaril** [comment] 2019-01-20 00:56
Interesting...

Just for reference if you want to keep looking into it on your own, DS does not alter the vanilla pathfinding algorithm.

In any case, I have no way of (reasonably) doing any of my own tests or workarounds without your modpack, so for now you're on your own.  I'm going to close this issue since I can't (reasonably) take action on it right now.

I don't receive notifications on closed issues IIRC, so if you decide you want me to look into it at some point, please post a new issue with a link to a modpack download (doesn't have to be a curseforge link; can just be a zip/rar file you've uploaded somewhere).  In the meantime, good luck!

**Comment by Laike-Endaril** [comment] 2019-01-20 20:58
Nvm, I was half asleep.  More than half asleep, actually.  I've been able to reproduce this with only DS and Adventure Tools.  I'll do more testing and see what I find.

**Comment by Laike-Endaril** [comment] 2019-01-20 21:14
I've confirmed this happening *without* DS as well.  This crash happens with *only* Adventure Tools installed on an otherwise vanilla game, so I've reported it on his issue tracker and referenced this issue.

[https://github.com/brobotato/adventurepack/issues/2](https://github.com/brobotato/adventurepack/issues/2)

This officially has nothing to do with DS, so *now* I'll close it XD

**Closed as completed by Laike-Endaril** 2019-01-20 21:14 UTC

**Comment by syntacticsplenda** [comment] 2019-01-21 04:26
Thanks, I'll look into this.
