### ISSUE TITLE
Ice and Fire

### ISSUE THREAD

**Issue by Fortist** [Laike-Endaril/Dynamic-Stealth#32] opened 2019-02-20 03:22 UTC
It's a long shot but it's what I got. Certain creatures seem to crash my game when they're around and I have Dynamic Stealth.
https://github.com/Alex-the-666/Ice_and_Fire/issues/1425#issue-412225847

Or when a Cyclops eats a wizard from Electroblob's Wizardy.

After removing DS, all seems to be fine

**Comment by Laike-Endaril** [comment] 2019-02-20 04:51
Hey, I already know the cause.  I'll post in the other thread to keep information in one place.

**Comment by Laike-Endaril** [comment] 2019-02-20 05:30
I should have this mostly fixed in my indev version now.

The only thing still concerning me is the Cyclops part.  I'd think my filter should be catching that one already.  Which version of dynamic stealth were you using?

**Comment by Fortist** [comment] 2019-02-20 12:36
Oh, I havent checked Cyclops in a while so I dont know if it's still affecting me, but the latest of 2.054.

**Comment by Laike-Endaril** [comment] 2019-02-20 20:52
I've released a new version (055) which should fix any issues with dragons, hippogryphs, and sea serpents (which I'm not sure are officially released yet).

If you get a crash with the cyclops, please post a new issue with the log and I'll look into it.

Ofc if you get the crash you posted here again, please tell me that as well, but that should not happen.

**Closed as completed by Laike-Endaril** 2019-02-20 20:52 UTC
