### ISSUE TITLE
Issue with Abyssalcraft?

### ISSUE THREAD

**Issue by edenhack** [Laike-Endaril/Dynamic-Stealth#42] opened 2019-04-01 08:30 UTC
[crash-2019-04-01_08.26.29-server.txt](https://github.com/Laike-Endaril/Dynamic-Stealth/files/3028395/crash-2019-04-01_08.26.29-server.txt)

**Comment by edenhack** [comment] 2019-04-01 13:14
as a temp fix i set all abyssalcraft mobs to threat bypass, but just wanted to post this, maybe it can help with idk, identifying why custom mobs have errors like this.

**Comment by Laike-Endaril** [comment] 2019-04-01 22:22
Thanks for the report!

This is a fairly common issue which has to do with a certain mistake in AI programming that doesn't normally cause issues...until DS is running alongside those AI tasks.

I actually have a system in place to deal with this particular issue, but it's only semi-auto (it doesn't catch every offending AI task), so sometimes I need to add stuff manually.  I will go through the Abyssalcraft AI tasks and add the ones which cause the issue.

This should be fixed in version 067 when it comes out.



If you are (or anyone reading this is) interested in slightly more technical details:

The root of the issue is that the AI checks to make sure its attack target is not null in the "shouldExecute()" method, and expects it to still not be null in the "updateTask()" method.  This is flawed logic, because all other AI tasks get a chance to run methods between your AI task's "updateTask()" and "shouldExecute()" methods, and may very well set the attack target to null if they want, which is exactly what DS does in order to enforce its stealth system.

**Comment by edenhack** [comment] 2019-04-01 22:32
I see, makes a lot of sense. Either way the bypass feature works at avoiding this error so it's no big issue. Please take your time and dont burn out trying to add all the custom ai tracking. I really appreciate the work you have put into this mod and the config is to die for it's so configurable.Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: Laike-Endaril <notifications@github.com> Date: 4/1/19  5:22 PM  (GMT-06:00) To: Laike-Endaril/Dynamic-Stealth <Dynamic-Stealth@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Laike-Endaril/Dynamic-Stealth] Issue with Abyssalcraft? (#42) Thanks for the report!
This is a fairly common issue which has to do with a certain mistake in AI programming that doesn't normally cause issues...until DS is running alongside those AI tasks.
I actually have a system in place to deal with this particular issue, but it's only semi-auto (it doesn't catch every offending AI task), so sometimes I need to add stuff manually.  I will go through the Abyssalcraft AI tasks and add the ones which cause the issue.
This should be fixed in version 067 when it comes out.
If you (or anyone reading this) is interested in slightly more technical details:
The root of the issue is that the AI checks to make sure its attack target is not null in the "shouldExecute()" method, and expects it to still not be null in the "updateTask()" method.  This is flawed logic, because all other AI tasks get a chance to run methods between your AI task's "updateTask()" and "shouldExecute()" methods, and may very well set the attack target to null if they want, which is exactly what DS does in order to enforce its stealth system.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Laike-Endaril/Dynamic-Stealth","title":"Laike-Endaril/Dynamic-Stealth","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Laike-Endaril/Dynamic-Stealth"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Laike-Endaril in #42: Thanks for the report!\r\n\r\nThis is a fairly common issue which has to do with a certain mistake in AI programming that doesn't normally cause issues...until DS is running alongside those AI tasks.\r\n\r\nI actually have a system in place to deal with this particular issue, but it's only semi-auto (it doesn't catch every offending AI task), so sometimes I need to add stuff manually.  I will go through the Abyssalcraft AI tasks and add the ones which cause the issue.\r\n\r\nThis should be fixed in version 067 when it comes out.\r\n\r\n\r\n\r\nIf you (or anyone reading this) is interested in slightly more technical details:\r\n\r\nThe root of the issue is that the AI checks to make sure its attack target is not null in the \"shouldExecute()\" method, and expects it to still not be null in the \"updateTask()\" method.  This is flawed logic, because all other AI tasks get a chance to run methods between your AI task's \"updateTask()\" and \"shouldExecute()\" methods, and may very well set the attack target to null if they want, which is exactly what DS does in order to enforce its stealth system."}],"action":{"name":"View Issue","url":"https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478768893"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478768893",
"url": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478768893",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Laike-Endaril** [comment] 2019-04-01 22:38
Yeah, the bypass will always prevent the crash when this happens, so it's a good temporary solution (kudos on figuring that out without asking btw).  It does have some side-effects though, ie. the mob won't use the threat system obviously, but less obviously, the mob will not use the DS AI (because it relies on the threat system).

In any case, it won't take long to add the AI tasks to my filter, probably less than 15 mins (because AC doesn't have many AI tasks to go through), so not a problem ;)

**Comment by edenhack** [comment] 2019-04-01 22:46
Ok, I really appreciate it. Your work is fantastic!Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: Laike-Endaril <notifications@github.com> Date: 4/1/19  5:38 PM  (GMT-06:00) To: Laike-Endaril/Dynamic-Stealth <Dynamic-Stealth@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Laike-Endaril/Dynamic-Stealth] Issue with Abyssalcraft? (#42) Yeah, the bypass will always prevent the crash when this happens, so it's a good temporary solution (kudos on figuring that out without asking btw).  It does have some side-effects though, ie. the mob won't use the threat system obviously, but less obviously, the mob will not use the DS AI (because it relies on the threat system).
In any case, it won't take long to add the AI tasks to my filter, probably less than 15 mins (because AC doesn't have many AI tasks to go through), so not a problem ;)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Laike-Endaril/Dynamic-Stealth","title":"Laike-Endaril/Dynamic-Stealth","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Laike-Endaril/Dynamic-Stealth"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Laike-Endaril in #42: Yeah, the bypass will always prevent the crash when this happens, so it's a good temporary solution (kudos on figuring that out without asking btw).  It does have some side-effects though, ie. the mob won't use the threat system obviously, but less obviously, the mob will not use the DS AI (because it relies on the threat system).\r\n\r\nIn any case, it won't take long to add the AI tasks to my filter, probably less than 15 mins (because AC doesn't have many AI tasks to go through), so not a problem ;)"}],"action":{"name":"View Issue","url":"https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478772575"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478772575",
"url": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478772575",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Laike-Endaril** [comment] 2019-04-02 04:24
This is now fixed in the latest release (067)!  Don't forget to turn threat bypass back off if you want

**Closed as completed by Laike-Endaril** 2019-04-02 04:24 UTC

**Comment by edenhack** [comment] 2019-04-02 04:30
Hey thanks so much!Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: Laike-Endaril <notifications@github.com> Date: 4/1/19  11:24 PM  (GMT-06:00) To: Laike-Endaril/Dynamic-Stealth <Dynamic-Stealth@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Laike-Endaril/Dynamic-Stealth] Issue with Abyssalcraft? (#42) This is now fixed in the latest release (067)!  Don't forget to turn threat bypass back off if you want

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Laike-Endaril/Dynamic-Stealth","title":"Laike-Endaril/Dynamic-Stealth","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Laike-Endaril/Dynamic-Stealth"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Laike-Endaril in #42: This is now fixed in the latest release (067)!  Don't forget to turn threat bypass back off if you want"}],"action":{"name":"View Issue","url":"https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478839281"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478839281",
"url": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478839281",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by edenhack** [comment] 2019-04-02 04:32
I believe I have another monster you should check into what exactly its doing although that is totally up to you. The mod Magma monsters also throws an exception. I can make another issue if you would like to investigate this. I'm merely on my phone and not at home at the moment.Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: Laike-Endaril <notifications@github.com> Date: 4/1/19  11:24 PM  (GMT-06:00) To: Laike-Endaril/Dynamic-Stealth <Dynamic-Stealth@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Laike-Endaril/Dynamic-Stealth] Issue with Abyssalcraft? (#42) This is now fixed in the latest release (067)!  Don't forget to turn threat bypass back off if you want

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Laike-Endaril/Dynamic-Stealth","title":"Laike-Endaril/Dynamic-Stealth","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Laike-Endaril/Dynamic-Stealth"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Laike-Endaril in #42: This is now fixed in the latest release (067)!  Don't forget to turn threat bypass back off if you want"}],"action":{"name":"View Issue","url":"https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478839281"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478839281",
"url": "https://github.com/Laike-Endaril/Dynamic-Stealth/issues/42#issuecomment-478839281",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Laike-Endaril** [comment] 2019-04-02 13:00
Yes, if you could post another crash report or log file in a new issue that would be great.  It will let me identify the problem easier (I imagine it may be the same as what happened with AC, but don't know for sure).

It will also let me handle the issue in a more organized way in general

**Comment by Laike-Endaril** [comment] 2019-04-02 14:16
Nvm, I've found and fixed the Magma Monsters issue already (in the next version; 068).

But just in general, yes, I prefer separate issues for each mod compat
