### ISSUE TITLE
Crash with TickDynamic

### ISSUE THREAD

**Issue by Versimno** [Laike-Endaril/Dynamic-Stealth#10] opened 2019-01-06 06:13 UTC
Using DynamicStealth-1.12.2.0.20+ along with the latest Tick Dynamic (1.12.2-1.0.1), the following crash occurs upon loading a world: https://paste.dimdev.org/ofuxubacux.mccrash (crash catched by VanillaFix)

Im using Forge 1.12.2-14.23.5.2806, along with like 100 other mods (None of them seemed to conflict as far as I know below DynamicStealth version 1.12.2.0.20)

**Comment by Versimno** [comment] 2019-01-06 06:15
I also tried it with Forge 1.12.2-14.23.5.2796 (a more stable release) and the same crash occurs

**Comment by Laike-Endaril** [comment] 2019-01-06 19:44
I'm pretty sure a NotImplementedException (which is what you're getting there) is only supposed to be used explicitly by developers for features which are not yet implemented.  Ie. this is an issue on Tick Dynamic's end.  I don't even think there's a way for me to fix it from my end

Whatever their system is trying to do seems to be breaking because they haven't built support for a certain situation yet, namely this bit of code from my source:

`Entity[] loadedEntities = player.world.loadedEntityList.toArray(new Entity[player.world.loadedEntityList.size()]);
`

The toArray(T[]) function here is what it seems to have an issue with.

I'll leave this open for now, but you should post an issue on Tick Dynamic's issue tracker for this and see what they say.  Feel free to reference this issue so they can read my comment here; might make it easier for them to debug it.

**Comment by Laike-Endaril** [comment] 2019-01-07 22:58
Found the root cause, and it was exactly as I suspected; posted details over on the issue you made on TickDynamic's tracker.

Closing this one as the root cause lies in TickDynamic.

**Closed as completed by Laike-Endaril** 2019-01-07 22:58 UTC
