### ISSUE TITLE
Dynamic stealth stops Immersive Engineering railgun from firing.

### ISSUE THREAD

**Issue by supremedutchgamer** [Laike-Endaril/Dynamic-Stealth#53] opened 2019-06-07 03:43 UTC
it seems dynamic stealth stops the immersive engineering railgun from firing. it charges up fine, but then doesnt make the firing sound and no projectile gets fired. I feel like this is a dynamic-stealth issue, rather than an IE issue, but i'm not sure.

**Comment by Laike-Endaril** [comment] 2019-06-07 07:03
Thanks for the report!  I'll look into this.

**Comment by Laike-Endaril** [comment] 2019-06-07 07:11
Actually, I cannot reproduce this issue with the latest releases of Dynamic Stealth and Immersive Engineering.  I just shot a wolf dead with the railgun, with DS installed.

Can you run a test using *only* these two mods (and Fantastic Lib, since DS requires it)?

**Comment by supremedutchgamer** [comment] 2019-06-08 09:33
tested with just the two mods, even with the config from my pack, then i tried something else, I re-enabled Dynamic stealth, and disabled backstab (the mod linked on dynamic stealth's curseforge page). that fixed it as well. would this still make it a dynamic stealth issue or should i report this on the pages of backstab and immersive engineering?

**Comment by Laike-Endaril** [comment] 2019-06-08 15:23
Try it with just Backstab and IE, and see if it occurs.
If it still happens, then it's compat between Backstab and IE.
If it doesn't happen, then it's 3-way compat between Backstab, IE, and DS (hopefully not, as this may get complicated)

**Comment by Laike-Endaril** [comment] 2019-06-08 15:53
I just ran tests with...
...DS and IE
...BS and IE
...DS, BS, and IE

And the railgun worked fine in all of them.  I have no idea what's causing your issue.  Next time the railgun acts up, can you get the full log file, post it on pastebin / hastebin, and give me a link?  Preferably with as few mods installed as possible, but I'll take whatever I can get.

**Comment by supremedutchgamer** [comment] 2019-06-10 09:40
did a bunch more experimentation, and removing FXcontrol from my pack fixes the issue, so does removing morph. but adding DS, BS, IE, FXcontrol and morph to a seperate pack and copying over the configs does not recreate the issue.... so its something hyperspecific. anyways, i've decided to remove FXcontrol from the pack. as I hadnt used it for anything yet.

**Comment by Laike-Endaril** [comment] 2019-06-10 13:16
Huh, that's weird...I wouldn't think FX Control would do literally anything unless you specified it (though admittedly I haven't tried it; I just know about it because I'm using In Control).

Thanks for going through more of your mods to do more debugging.  I may try to look into this further just to see what I can find, so I'll leave the issue open, but I'll be concentrating on some other things first since you at least have a workaround for now (and because I feel like finding the root cause is going to be time consuming)

**Comment by Laike-Endaril** [comment] 2019-07-07 07:10
Actually I've gotten super busy, so I'll probably just be closing stuff with reasonable workarounds...can re-open if it turns out to be an issue again later (just respond here if so)

**Closed as completed by Laike-Endaril** 2019-07-07 07:10 UTC
